#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogDashboard.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\Views\_layout.cshtml"
    using LogDashboard.Views;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class _layout : LogDashboard.Views.RazorPage
    {
#line hidden

        /// <summary>
        /// 执行布局页面的渲染
        /// </summary>
        public override void Execute()
        {
            WriteLiteral("<!doctype html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <meta name=\"viewport\" content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0\">\r\n    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n    <title>日志面板</title>\r\n    <link href=\"");

            #line 12 "..\Views\_layout.cshtml"
            Write(Context.Options.PathMatch);
            #line default
            #line hidden

            WriteLiteral("/css.simple-line-icons.css\" rel=\"stylesheet\">\r\n    <link href=\"");

            #line 13 "..\Views\_layout.cshtml"
            Write(Context.Options.PathMatch);
            #line default
            #line hidden

            WriteLiteral("/css.bootstrap.min.css\" rel=\"stylesheet\">\r\n    <link href=\"");

            #line 14 "..\Views\_layout.cshtml"
            Write(Context.Options.PathMatch);
            #line default
            #line hidden

            WriteLiteral("/css.font-awesome.min.css\" rel=\"stylesheet\">\r\n    <link href=\"");

            #line 15 "..\Views\_layout.cshtml"
            Write(Context.Options.PathMatch);
            #line default
            #line hidden

            WriteLiteral("/css.tempusdominus-bootstrap-4.min.css\" rel=\"stylesheet\">\r\n    <link rel=\"stylesheet\" href=\"");

            #line 16 "..\Views\_layout.cshtml"
            Write(Context.Options.PathMatch);
            #line default
            #line hidden

            WriteLiteral("/css.styles.css\">\r\n</head>\r\n<body class=\"sidebar-fixed header-fixed\">\r\n    <div class=\"page-wrapper\">\r\n        ");

            #line 20 "..\Views\_layout.cshtml"
            if(Context.Options.EnableHeaderNav)
            {

            #line default
            #line hidden

            WriteLiteral("\r\n        <nav class=\"navbar page-header\">\r\n            <a href=\"#\" class=\"btn btn-link sidebar-mobile-toggle d-md-none mr-auto\">\r\n                <i class=\"fa fa-bars\"></i>\r\n            </a>\r\n            <a class=\"navbar-brand\" href=\"");

            #line 25 "..\Views\_layout.cshtml"
            Write(Context.Options.ExternalLink);
            #line default
            #line hidden

            WriteLiteral("\" target=\"_blank\">\r\n                <h2>");

            #line 26 "..\Views\_layout.cshtml"
            Write(Context.Options.Brand);
            #line default
            #line hidden

            WriteLiteral("</h2>\r\n            </a>\r\n            <a href=\"#\" class=\"btn btn-link sidebar-toggle d-md-down-none\">\r\n                <i class=\"fa fa-bars\"></i>\r\n            </a>\r\n            <ul class=\"navbar-nav ml-auto\">\r\n                <li class=\"nav-item d-md-down-none\">\r\n                    <a href=\"/\">\r\n                        <i class=\"fa fa-reply-all\"></i>\r\n\r\n                    </a>\r\n                </li>\r\n            </ul>\r\n        </nav>\r\n        ");

            #line 40 "..\Views\_layout.cshtml"
            }

            #line default
            #line hidden

            WriteLiteral("\r\n        <div class=\"main-container\">\r\n            <div class=\"sidebar\">\r\n                <nav class=\"sidebar-nav\">\r\n                    <ul class=\"nav\">\r\n                        <li class=\"nav-title\">菜单</li>\r\n                        <li class=\"nav-item\">\r\n                            <a id=\"mapPath\" href=\"");

            #line 47 "..\Views\_layout.cshtml"
            Write(Context.Options.PathMatch);
            #line default
            #line hidden

            WriteLiteral("\" class=\"nav-link ");

            #line 47 "..\Views\_layout.cshtml"
            Write(ViewData["dashboardNav"]);
            #line default
            #line hidden

            WriteLiteral(">\r\n                                <i class=\"icon icon-speedometer\"></i> Dashboard\r\n                            </a>\r\n                        </li>\r\n                        <li class=\"nav-item\">\r\n                            <a href=\"");

            #line 52 "..\Views\_layout.cshtml"
            Write(Context.Options.PathMatch);
            #line default
            #line hidden

            WriteLiteral("/Dashboard/BasicLog\" class=\"nav-link ");

            #line 52 "..\Views\_layout.cshtml"
            Write(ViewData["basicLogNav"]);
            #line default
            #line hidden

            WriteLiteral(">\r\n                                <i class=\"icon icon-target\"></i> 日志\r\n                            </a>\r\n                        </li>\r\n                    </ul>\r\n                </nav>\r\n            </div>\r\n            <div class=\"content\" id=\"content\">\r\n                <div class=\"content-box\">\r\n                    ");

            #line 61 "..\Views\_layout.cshtml"
            Write(RenderBody());
            #line default
            #line hidden

            WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <script src=\"");

            #line 66 "..\Views\_layout.cshtml"
            Write(Context.Options.PathMatch);
            #line default
            #line hidden

            WriteLiteral("/js.jquery.min.js\"></script>\r\n    <script src=\"");

            #line 67 "..\Views\_layout.cshtml"
            Write(Context.Options.PathMatch);
            #line default
            #line hidden

            WriteLiteral("/js.Chart.min.js\"></script>\r\n    <script src=\"");

            #line 68 "..\Views\_layout.cshtml"
            Write(Context.Options.PathMatch);
            #line default
            #line hidden

            WriteLiteral("/js.bootstrap.min.js\"></script>\r\n    <script src=\"");

            #line 69 "..\Views\_layout.cshtml"
            Write(Context.Options.PathMatch);
            #line default
            #line hidden

            WriteLiteral("/js.moment.min.js\"></script>\r\n    <script src=\"");

            #line 70 "..\Views\_layout.cshtml"
            Write(Context.Options.PathMatch);
            #line default
            #line hidden

            WriteLiteral("/js.tempusdominus-bootstrap-4.js\"></script>\r\n    <script src=\"");

            #line 71 "..\Views\_layout.cshtml"
            Write(Context.Options.PathMatch);
            #line default
            #line hidden

            WriteLiteral("/js.spin.min.js\"></script>\r\n    <script src=\"");

            #line 72 "..\Views\_layout.cshtml"
            Write(Context.Options.PathMatch);
            #line default
            #line hidden

            WriteLiteral("/js.log.js\"></script>\r\n    ");

            #line 73 "..\Views\_layout.cshtml"
            Write(RenderSection("Scripts"));
            #line default
            #line hidden

            WriteLiteral("\r\n</body>\r\n</html>");
        }
    }
}